import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
        h2 {
          font-size: 35px;
        }
        h3 {
          font-size: 25px;
        }
      `}</style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="dummy">Hunting Coder</span>
        </h1>
        <div className={styles.imagewrap}>
          <Image
            className={styles.myImg}
            src="/homeimg.avif"
            width={300}
            height={200}
          />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coders
        </p>

        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to Learn Javascript</h3>
            <p>Javascript is the language used to design for the web </p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to Learn Javascript</h3>
            <p>Javascript is the language used to design for the web </p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to Learn Javascript</h3>
            <p>Javascript is the language used to design for the web </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
